### ISSUE TITLE
Dyld Symbol not found

### ISSUE THREAD

**Issue by rob-bc** [sttz/expresso#1]
Receiving the error below after a successful install. Not sure if it's down to my system config but thought I would share with you to see if you had any ideas. Not sure what other information you might need!

* macOS 10.10
* mono  v 5.4.0.201

```
~|⇒  brew cask reinstall expresso
Warning: Calling brew cask reinstall is deprecated! Use brew reinstall instead.
==> Downloading https://github.com/sttz/expresso/releases/download/1.0.2/expresso-1.0.2.zip
Already downloaded: /Users/MMS/Library/Caches/Homebrew/downloads/ec49d826036c4efe760072f3fa0f9a563f24fa0fd51cf1ba4785e7096e681618--expresso-1.0.2.zip
==> Verifying SHA-256 checksum for Cask 'expresso'.
==> Uninstalling Cask expresso
==> Unlinking Binary '/usr/local/bin/expresso'.
==> Purging files for version 1.0.2 of Cask expresso
==> Installing Cask expresso
==> Linking Binary 'expresso' to '/usr/local/bin/expresso'.
🍺  expresso was successfully installed!


~|⇒  expresso
dyld: Symbol not found: _kSecKeyAlgorithmRSAEncryptionRaw
  Referenced from: /usr/local/bin/expresso
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /usr/local/bin/expresso
[1]    6306 trace trap  expresso
```

**Comment by sttz** [comment]
Hey, you're trying to use the pre-built binary that is built using CoreRT. CoreRT is experimental and they don't publish any official system requirements but the missing symbol was only added in macOS 10.12. So I suspect your version of macOS 10.10 is not supported by CoreRT.

I suggest you try to install from source using the formula instead. It uses mono, which should support macOS 10.9+ but I am not set up to test on macOS 10.10 to actually verify.

```
brew cask install sttz/tap/expresso
```

**Comment by rob-bc** [comment]
Great thank you - everything working well now!
