### ISSUE TITLE
Select Random Location, Not the Closest

### ISSUE THREAD

**Issue by hdanirwin** [sttz/expresso#2]
Hi there, 

Is there any way to select a random VPN within the USA? Right now when I type in "connect USA" it keeps giving me the same one.

**Comment by sttz** [comment]
I've released version 1.1.0, which adds the `--random` option to select a random location within a country.

Note that you need to use the exact country name or two-letter country code as listed by `expresso locations`. For the USA, you either have to use `expresso connect --random "United States"` or `expresso connect --random US`.

Using `expresso connect USA` will do a text search and pick the first matching location, the `--random` option does not apply here.

**Comment by hdanirwin** [comment]
That’s great, I’ll check it out. 

Thanks for making this!
