### ISSUE TITLE
Get VPN status

### ISSUE THREAD

**Issue by james-rose** [sttz/expresso#4]
Is there a way to retrieve the VPN status (ie VPN Connected or not connected?).  Is this even possible through the web api?

**Comment by sttz** [comment]
It's possible with the library but the CLI doesn't currently expose this information.

You could call `expresso alfred` and when connected, the first entry in the JSON output has a ⚡️ icon and disconnect argument.

**Comment by james-rose** [comment]
The `expresso alfred` call works perfectly for this.  Many thanks!
