### ISSUE TITLE
Can this command used in Windows Plaftform

### ISSUE THREAD

**Issue by havid0707** [sttz/expresso#6]
Hey, 

this project can only be used in iOS/Linux, is it right?

**Comment by havid0707** [comment]
Find the solution

**Comment by Tetsukick** [comment]
@havid0707 
sorry may I ask your solution?
I m also facing the issue can not open expresso in windows.

**Comment by Tetsukick** [comment]
oh just type 'expressvpn.exe locations' in command prompt.  
works well.
