### ISSUE TITLE
Windows invalid extension Id case

### ISSUE THREAD

**Issue by havid0707** [sttz/expresso#7]
Hi @sttz ,

The structure of manifest as below:
struct NativeMessagingManifest
    {
        public string name;
        public string description;
        public string path;
        public string type;
        public string[] allowed_extensions;
    }

But my windows10 com.expressvpn.helper.json as Below:
{
  "name": "com.expressvpn.helper",
  "description": "ExpressVPN Chrome Helper",
  "path": "C:\\Program Files (x86)\\ExpressVPN\\expressvpnd\\expressvpn-browser-helper.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://fgddmllnllkalaagkghckoinaemmogpe/",
    "chrome-extension://olhkmmhcabcohlcodnbkfoekafimgkmb/",
    "chrome-extension://gicmddjpmepnbabhkhihlgdfccbppflm/"
  ]
}

If I  change allowed_origins to allowed_extensions, the program still promt "invalid  chrome extendsion id!"
I have check the extendsion installed in chrome, it is the first one in the list. May I know this program tested under windows? or this program only compatible with specific version ExpressVPN?

**Comment by havid0707** [comment]
In Widnows, the origins is the first parameter. I solved this by Google

**Comment by sttz** [comment]
Yeah, I've only tested on macOS. If you get it running on Windows, a PR would be welcome!

**Comment by darek292** [comment]
> In Widnows, the origins is the first parameter. I solved this by Google

Could you share your solution if possible? I'm looking for a CLI client as well on Windows as I need to reconnect programmatically with ExpressVPN

**Comment by lord-ne** [comment]
I've somewhat solved this. You need to change all references to "com.expressvpn.helper" to "com.expressvpn.helper.firefox". On Windows they are two separate files. You also need to add "C:/Program Files (x86)/ExpressVPN/expressvpnd" to the variable manifestBasePaths.
